version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiber-app
    hostname: fiber-app
    volumes:
      - ./:/app
    ports:
      - 3010:3000
    command: air -c .air.toml
    networks:
      - gofiber-net

networks:
  gofiber-net: ~